### ISSUE TITLE
Can ffmpeg plugin support yuv420p output?

### ISSUE THREAD

**Issue by HermanChen** [imageio/imageio#327]
I am try to get yuv420p output from ffmpeg plugin. But I found it is always output rgb format as ffmpeg image2pipe configuration.
How can I get yuv420p output from typical video file using imageio?

**Comment by almarklein** [comment]
So your problem is solved?

**Comment by HermanChen** [comment]
No, the problem is still there. I get a reader from get_reader(file, 'ffmpeg') but I still can not get yuv420 output from the reader.

**Comment by almarklein** [comment]
See also `pixelformat` in http://imageio.readthedocs.io/en/stable/format_ffmpeg.html#ffmpeg.

I am not entirely sure what you want, and how it is different from what you get. Do you your read numpy arrays to be yuv?

**Comment by HermanChen** [comment]
`import imageio`
`reader = imageio.get_reader('/home/herman/work/debug/tennis200.h264', 'ffmpeg', pixelformat='nv12', print_info='true'`
`img = reader.get_data(0)`

Then I found the numpy img is always RGB not YUV420. I want to get yuv data from reader.

**Comment by almarklein** [comment]
The output pixel format (i.e. what is read in) is currently hardcoded to be rgb24. If you're interested, I'm open to a PR to make the plugin more flexible.

**Comment by almarklein** [comment]
The output pixel format (i.e. what is read in) is currently hardcoded to be rgb24. https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py#L349
If you're interested, I'm open to a PR to make the plugin more flexible.

**Comment by HermanChen** [comment]
OK, thanks : )
