### ISSUE TITLE
Can't install 2.4.0

### ISSUE THREAD

**Issue by eguendelman** [imageio/imageio#378]
ubuntu 14.04, python 2.7.6, pip 18.0
Trying to install imageio using `pip install imageio` gives
```
Collecting imageio
  Using cached https://files.pythonhosted.org/packages/ac/64/8e2bb6aac43d6ed7c2d9514320b43d5e80c00f150ee2b9408aee24359e6d/imageio-2.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in imageio setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Ka8LjP/imageio/
```

**Comment by almarklein** [comment]
cc @clbarnes Any idea what this could be? I can install just fine on Python 2.7 (Win10).

**Comment by almarklein** [comment]
Spun up a VM and I can reproduce the error. Looking into it...

**Comment by almarklein** [comment]
The problem is this bit in `steup.py`:
```py
    install_requires=[
        "numpy",
        "pillow",
        'enum34; python_version < "3.4"',
        'futures; python_version < "3.2"',
    ],
```

Not sure why it fails, because we do test installation on Python 2.7 in CI. But its easy enough to fix by predefining `install_requires`, adding enum34 and futures depending on the value of `sys.version_info`. Seems to work on my VM at least.

**Comment by clbarnes** [comment]
I can also install fine on ubuntu, py2.7.15, pip18 - but my ubuntu is 18.04. Surprising that the ubuntu version is the difference given it's not running into issues with some compiled library. As you say, travis should be running a 14.04 image and it's passing there, which makes it even weirder. It would be nice to stick with the standard form of version-dependent requirements but whatever works!

**Comment by almarklein** [comment]
Fixed. Will do a dot-release as soon as I've wrapped up #377.

**Comment by almarklein** [comment]
2.4.1 is on pypi

**Comment by clbarnes** [comment]
Oh, that's probably it then, although I'm still not sure why as it's probably pip parsing those requirements. The travis image will probably be using a more recent version. Anything stopping you from upgrading from your 5-year-old version of an soon-to-be-deprecated language? :stuck_out_tongue:
